### ISSUE TITLE
Orbiter and 5015 Fan are too close

### ISSUE THREAD

**Issue by FanSails** [elcrni/Voron-Mods#10]
1、Orbiter and 5015 Fan are too close ，that Orbiter will be squeezed to Fan during installation. Whether the clearance between them can be increased to make assembly easier.
![微信截图_20230109122942](https://user-images.githubusercontent.com/38837338/211242053-05b62996-e2fc-48da-887c-4936f00dbae2.png)

2、Latch and body interfere. When manually loading Filament, Latch cannot be released well.
![20230109124308](https://user-images.githubusercontent.com/38837338/211242784-0442798d-5c67-4b6b-907d-ca298f2cba26.png)

3、I like your design very much, thank you for your development

**Comment by elcrni** [comment]
Thanks for the feedback.

1. This is now fixed, new files will be on GH today. 0.75mm is the distance now, although it worked just fine for me with the previous version, without any gap or issues.
2. They do interfere with SB cover and that was never in question. I dont plan to change that, first as i never ever use the lever (apart from major maintenance but the the SB cover if of the body anyway) and second as i do not want to cut the SB body for that.
3. thank you!

**Comment by elcrni** [comment]
Fixed

**Comment by Hellrox** [comment]
@elcrni what brand do you use ? I tried a Sunon MF50152VX-1L02C-A99 but it doesn't fit well
I'll order and try a GDSTIME probably

**Comment by elcrni** [comment]
> @elcrni what brand do you use ? I tried a Sunon MF50152VX-1L02C-A99 but it doesn't fit well
> I'll order and try a GDSTIME probably

Gdstime usually.

**Comment by Hellrox** [comment]
@elcrni The Gdstime dosen't fit as well, I'll contact Layerguru, maybe they printed the older version.

**Comment by Heerozh** [comment]
I found that the official 3D model is wrong. For example, the front face I bought is 0.26mm thicker than the 3d mockup. The screws part of the LDO motor are 0.7mm thicker. I used your latest model and still can't fit it in. 5015 still needs about 1.5mm deeper

**Comment by elcrni** [comment]
> I found that the official 3D model is wrong. For example, the front face I bought is 0.26mm thicker than the 3d mockup. The screws part of the LDO motor are 0.7mm thicker. I used your latest model and still can't fit it in. 5015 still needs about 1.5mm deeper

New, redesigned front cover is now in STL folder, deeper than initial and will accommodate any part cooling fan
